
[package]
name = "subpar_test"
version = "0.0.0"
authors = ["Dave Fogelson <dfogelson@fishheadlabs.com>"]
license = "MIT"
edition = "2018"
publish = false


[dependencies]
subpar = { path = "../subpar" }
subpar_derive = { path = "../subpar_derive" }
chrono = "0.4.7"
